/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedStartupsIdRouteImport } from './routes/_authenticated/startups.$id'
import { Route as AuthenticatedAdminNewRouteImport } from './routes/_authenticated/admin.new'
import { Route as AuthenticatedAdminJudgesRouteImport } from './routes/_authenticated/admin.judges'
import { Route as AuthenticatedStartupsIdFinancialRouteImport } from './routes/_authenticated/startups.$id.financial'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedStartupsIdRoute = AuthenticatedStartupsIdRouteImport.update({
  id: '/startups/$id',
  path: '/startups/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminNewRoute = AuthenticatedAdminNewRouteImport.update({
  id: '/admin/new',
  path: '/admin/new',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminJudgesRoute =
  AuthenticatedAdminJudgesRouteImport.update({
    id: '/admin/judges',
    path: '/admin/judges',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStartupsIdFinancialRoute =
  AuthenticatedStartupsIdFinancialRouteImport.update({
    id: '/financial',
    path: '/financial',
    getParentRoute: () => AuthenticatedStartupsIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/admin/judges': typeof AuthenticatedAdminJudgesRoute
  '/admin/new': typeof AuthenticatedAdminNewRoute
  '/startups/$id': typeof AuthenticatedStartupsIdRouteWithChildren
  '/startups/$id/financial': typeof AuthenticatedStartupsIdFinancialRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/admin/judges': typeof AuthenticatedAdminJudgesRoute
  '/admin/new': typeof AuthenticatedAdminNewRoute
  '/startups/$id': typeof AuthenticatedStartupsIdRouteWithChildren
  '/startups/$id/financial': typeof AuthenticatedStartupsIdFinancialRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/admin/judges': typeof AuthenticatedAdminJudgesRoute
  '/_authenticated/admin/new': typeof AuthenticatedAdminNewRoute
  '/_authenticated/startups/$id': typeof AuthenticatedStartupsIdRouteWithChildren
  '/_authenticated/startups/$id/financial': typeof AuthenticatedStartupsIdFinancialRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/sitemap.xml'
    | '/dashboard'
    | '/admin/judges'
    | '/admin/new'
    | '/startups/$id'
    | '/startups/$id/financial'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/sitemap.xml'
    | '/dashboard'
    | '/admin/judges'
    | '/admin/new'
    | '/startups/$id'
    | '/startups/$id/financial'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/sitemap.xml'
    | '/_authenticated/dashboard'
    | '/_authenticated/admin/judges'
    | '/_authenticated/admin/new'
    | '/_authenticated/startups/$id'
    | '/_authenticated/startups/$id/financial'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/startups/$id': {
      id: '/_authenticated/startups/$id'
      path: '/startups/$id'
      fullPath: '/startups/$id'
      preLoaderRoute: typeof AuthenticatedStartupsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/new': {
      id: '/_authenticated/admin/new'
      path: '/admin/new'
      fullPath: '/admin/new'
      preLoaderRoute: typeof AuthenticatedAdminNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/judges': {
      id: '/_authenticated/admin/judges'
      path: '/admin/judges'
      fullPath: '/admin/judges'
      preLoaderRoute: typeof AuthenticatedAdminJudgesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/startups/$id/financial': {
      id: '/_authenticated/startups/$id/financial'
      path: '/financial'
      fullPath: '/startups/$id/financial'
      preLoaderRoute: typeof AuthenticatedStartupsIdFinancialRouteImport
      parentRoute: typeof AuthenticatedStartupsIdRoute
    }
  }
}

interface AuthenticatedStartupsIdRouteChildren {
  AuthenticatedStartupsIdFinancialRoute: typeof AuthenticatedStartupsIdFinancialRoute
}

const AuthenticatedStartupsIdRouteChildren: AuthenticatedStartupsIdRouteChildren =
  {
    AuthenticatedStartupsIdFinancialRoute:
      AuthenticatedStartupsIdFinancialRoute,
  }

const AuthenticatedStartupsIdRouteWithChildren =
  AuthenticatedStartupsIdRoute._addFileChildren(
    AuthenticatedStartupsIdRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedAdminJudgesRoute: typeof AuthenticatedAdminJudgesRoute
  AuthenticatedAdminNewRoute: typeof AuthenticatedAdminNewRoute
  AuthenticatedStartupsIdRoute: typeof AuthenticatedStartupsIdRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedAdminJudgesRoute: AuthenticatedAdminJudgesRoute,
  AuthenticatedAdminNewRoute: AuthenticatedAdminNewRoute,
  AuthenticatedStartupsIdRoute: AuthenticatedStartupsIdRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
